Update nextjs.yml

diff --git a/nextjs.yml b/nextjs.yml
--- a/nextjs.yml
+++ b/nextjs.yml
@@ -79,6 +79,13 @@ jobs:
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./dist
+      - name: Check files after build
+  run: |
+    echo "Listing root folder:"
+    ls -la
+    echo "Listing dist folder:"
+    ls -la dist || echo "dist folder not found"
+
 
   # Deployment job
   deploy:
